[project]
name = "ufo-delivery"
version = "0.1.0"
description = "ğŸŸ FastAPI backend service for a simple operator-assisted food delivery"
readme = "README.md"
requires-python = ">=3.13.3"
dependencies = [
    "aiomysql>=0.2.0",
    "alembic>=1.16.4",
    "cryptography>=45.0.5",
    "fastapi>=0.116.1",
    "passlib[bcrypt]>=1.7.4",
    "pydantic-settings>=2.10.1",
    "pyjwt>=2.10.1",
    "python-multipart>=0.0.20",
    "sqlalchemy>=2.0.42",
    "uvicorn>=0.35.0",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
